const REQUIRED_CONDITION_MISSING = "REQUIRED_CONDITION_MISSING";
const REQUIRED_CONDITION_PARAMETER_MISSING = "REQUIRED_CONDITION_PARAMETER_MISSING";
const REQUIRED_RULE_PARAMETER_MISSING = "REQUIRED_RULE_PARAMETER_MISSING";
const REQUIRED_RULE_DEPENDENCY_MISSING = "REQUIRED_RULE_DEPENDENCY_MISSING";

module.exports = {
    REQUIRED_CONDITION_MISSING,
    REQUIRED_CONDITION_PARAMETER_MISSING,
    REQUIRED_RULE_DEPENDENCY_MISSING,
    REQUIRED_RULE_PARAMETER_MISSING
};